# -*- coding: utf-8 -*-
"""[Template] Int. Comp. Numérica-Trabalho #5 - 2023.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxt8nU1MmDLYcbGbEIwhBRBOssCSIsWp

#Trabalho prático # 5
##Introdução à Computação Numérica

###Tópico: Solução de Problemas de Valor Inicial (PVI)

---

Nome: *(preencher)*

DRE: *(preencher)*


---

**Instruções:**

**Preencha o notebook** com seus dados, seus códigos e **rode todos os códigos**

**Inclua  um relatório, na parte final do notebook,** com suas conclusões, respostas, observações e comentários relacionados com os tópicos e questões abordadas nas tarefas.  

**A elaboração dos códigos pode ser realizada em duplas, mas o resto do trabalho é individual.**

*Se você fez o seu trabalho em dupla inclua essa informação no relatório. Além disso, se você  também recebeu ajuda de um(a) colega/amigo(a) ou consultou/usou informações da internet ou outras fontes, coloque referências à elas no seu relatório.*


**Entrega do trabalho:**

*Data de entrega: 12/julho/2023*

---

## Tarefa #1:

 Desenvolver códigos, na forma de funções que implementem:

a) O Método de Euler.

b) O Método  de Euler aperfeiçoado (ou Método de Heun).

c) O Método de Runge-Kutta clássico de quarta ordem.
"""

# Adicione aqui sua função correspondente ao item a)

# Adicione aqui sua função correspondente ao item b)

# Adicione aqui sua função correspondente ao item c)

"""
## Tarefa #2: Paraquedista em queda livre

Utilize os seus códigos (da tarefa anterior, itens a), b) e c) ) para responder a seguinte questão.   
**Qual será a velocidade vertical atingida  por um paraquedista em queda livre (a velocidade inicial é nula), $25\,s$ após o salto?**


a) Considere que a taxa de variação instantânea da velocidade do paraquedista é dada pela EDO
$$\frac{dv}{dt}=g-\frac{c}{m} v, $$
onde $g=9.81\,m/s^2$ é a aceleração da gravidade, $m=75\,kg$ é a massa do paraquedista e $c=12.5\,kg/s$ é o coeficiente de arrasto correspondente ao paraquedas.

Para cada método implementado determine um número de passos tal que o erro na aproximação da velocidade final $v(25)$ seja inferior a $10^{-2}$, se sabemos que o valor exato da velocidade  pode ser calculado pela fórmula
$$v(t) = \frac{gm}{c}\left( 1-e^{-(c/m)t}\right).$$

Dica: Isto poderá ser feito por tentativa e erro.

b) Considere uma outra lei para a taxa de variação instantânea da velocidade do paraquedista dada pela EDO
$$\frac{dv}{dt}=g-\frac{C(v)}{m} v, $$
onde a função empiríca $C(v)$ que caracteriza a resistência do paraquedas é dada por
$$C(v) = c\left[1+\alpha \left(\frac{v}{v_{max}}\right)^\beta\right],$$
em que $c=12.5\,kg/s$, $\alpha=0.2$, $\beta =1.1$ e $v_{max} = 46\,m/s$.  (Observe que no caso $\alpha=0$ este modelo coincide com o apresentado no item a).)

Obtenha a velocidade final usando cada um dos métodos implementados considerando o mesmo número de passos definido no item a)).

c) Compare as velocidades obtidas nos itens a) e b).
"""

# Adicione aqui o código para resolver o item a)

# Adicione aqui o código para resolver o item b)

# Adicione aqui o código para resolver o item c)

"""## Tarefa #3: Propagação de uma doença infecciosa

Para modelar a dinâmica de uma doença infecciosa em que os indivíduos se recuperam sem imunidade, é usado o seguinte sistema de duas EDOs conhecido como modelo SIS:

$$
\left\{
\begin{aligned}
\frac{d S}{dt} &= -\beta S I + \gamma I\\
\frac{d I}{dt} &= \beta S I - \gamma I
\end{aligned}
\right.
$$

onde $S$ e $I$ representam o número de indivíduos suscetíveis e infectados, respectivamente, $t$ o tempo,  $\beta$ a velocidade de contacto ou infecção da doença e $\gamma$ a taxa de recuperação média.

Considere uma cidade com uma população de $10000$ indivíduos todos suscetíveis. Se um único indivíduo infectado entra na cidade to tempo $t = 0$, qual será a quantidade de indivíduos suscetíveis e infectados após $3$ semanas? Use os parâmetros $\beta = 0.0003/(\mathit{indivíduo\cdot dia})$ e $\gamma = 0.15/\mathit{dia}$.

Utilize o seu código do método de RK de $4^a$ ordem (tarefa #1, item c)) para responder a essa questão. Procure uma aproximação com erro estimado inferior a $0.05$. Explique.
"""

# Adicione aqui o código para resolver a questão

"""## Relatório

*Escreva aquí seu relatório.*
"""